# Generated by Django 3.1.2 on 2020-11-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20201110_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='longDescription',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='shortDescription',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
